name = "pdf-signer"
compatibility_date = "2024-09-05"

[site]
bucket = "./dist"

[[deployments]]
name = "production"
branch = "production-stable"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"